name: perestroika
summary: Perestroika
description: |
 An arcade game where you have to gather a crowd around you. Your followers will give you FAME. With your FAME you can acquire even more followers, but be careful of the red people. How many followers can you gain before the time runs out? The game supports both keyboard and controller input. This game was an entry for a game jam, more info on Github https://github.com/EliasVincent/godot-wild-jam-22-game
base: core18
version: "1.0"
grade: stable
confinement: strict
icon: ./snap-icon.png
apps:
  perestroika:
    command: ./Perestroika-Linux64.x86_64
    environment:
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
    plugs:
      - opengl
      - network
      - network-bind
      - pulseaudio
      - x11
      - desktop
      - joystick

parts:
  perestroika:
    source: ./
    source-type: local
    plugin: dump
    after: [desktop-glib-only]
    stage-packages:
        - libgl1-mesa-dri
        - libglu1-mesa
        - libgl1-mesa-glx
        - libpulse0
        - libxcursor1
        - libxinerama1
        - libxrandr2
        - libxi6
        - libasound2
  desktop-glib-only:  
      build-packages:
        - libglib2.0-dev
      plugin: make
      source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
      source-subdir: glib-only
      stage-packages:
        - libglib2.0-bin

